version: '3.8'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: docfav-villegas-web
    working_dir: /var/www/html
    volumes:
      - ./database:/var/www/html/database
    ports:
      - "8080:80"
